### ISSUE TITLE
Добавить в админку возможность удаления опроса/пользователя

### ISSUE THREAD

**Issue by KatySolo** [KatySolo/realtimepollreact#31]
По итогу обсуждения с Юлей пришли к выводу, что удаление будет через значок напротив сессии/пользователя. 
В итоге удалить слова про ограничения из README 

Подумать: 
- нужно ли дополнительно переспрашивать пользователя хочет ли он удалить

**Comment by JulieBlack666** [comment]
На данный момент можно спрашивать, хотим ли мы удалить пользователя встроенными возможностями языка, типа всплывающего окна в браузере. Потом, если захочется сделать всё покрасивее, можно подключить какие-нибудь попапы

**Comment by KatySolo** [comment]
> На данный момент можно спрашивать, хотим ли мы удалить пользователя встроенными возможностями языка, типа всплывающего окна в браузере. Потом, если захочется сделать всё покрасивее, можно подключить какие-нибудь попапы

Я думаю, что alert будет выглядить не очень классно на фоне уже имеющегося дизайна, так что лучше сделать сразу хорошо :)

Если это слишком запарно, то можно и alert (но это крайний случай уже)

**Comment by JulieBlack666** [comment]
Окей, поищу какое-нибудь красивое решение тогда

**Comment by KatySolo** [comment]
Попробуй не всплывающее окно на весь экран, что нибудь типа bubble от строчки.
Сейчас покидаю вариантики на макетах.

**Comment by JulieBlack666** [comment]
Окей, я всё равно пока серверной частью занимаюсь

**Comment by KatySolo** [comment]
ссылка на главный макет
https://www.figma.com/file/d5082EpG69nu2uxOubAwiV/Florette?node-id=98%3A90

окошки в коментриях
